name: Test Write API

on: 
  repository_dispatch:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.client_payload.type_ == 'Write'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and xlsxwriter #安装模块
      run: |
        pip install requests
        pip install xlsxwriter
    - name: Test APIs #api调用
      env:              
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        ACCOUNT: ${{ secrets.ACCOUNT }} 
        ACCOUNT_ADD: ${{ secrets.ACCOUNT_ADD }} 
        ACCOUNT_DEL: ${{ secrets.ACCOUNT_DEL }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}   
        OTHER_CONFIG: ${{ secrets.OTHER_CONFIG }}  
        EMAIL: ${{ secrets.EMAIL }}  
        TG_BOT: ${{ secrets.TG_BOT }}  
      run: |
        python ApiOfWrite.py
