name: Update Token

on: 
  repository_dispatch:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.client_payload.type_ == 'Update'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests和nacl模块
      run: |
        pip install requests
        pip install PyNaCl
    - name: Update token #更新token到secret
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息（修改以下，类推复制增加）
        APP_NUM: ${{ secrets.APP_NUM }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}
        #账号/应用1
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python UpdateToken.py
